name: Practice: Show a Secret

on:
  workflow_dispatch:

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print a masked secret
        run: echo "My secret is ${{ secrets.MY_TEST_SECRET }}"
