name: Practice: Write Secret to File (Encoded)

on:
  workflow_dispatch:

jobs:
  write-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Encode and write secret to file
        run: |
          echo -n "${{ secrets.MY_TEST_SECRET }}" | base64 > secret.txt
      - name: Show encoded file content
        run: cat secret.txt
      - name: Decode and print secret (for test)
        run: |
          echo "Decoded secret:"
          base64 --decode secret.txt || true
